apiVersion: v1
kind: PersistentVolume
metadata:
  name: localpv
  labels:
    type: local
spec:
  storageClassName: hostpath
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/C/Users/vmadmin/oraclepv"