apiVersion: v1
kind: ConfigMap
metadata:
  name: oracle-initsql-config
data:
  init.sql: |
    alter system set db_create_file_dest = '/opt/oracle/oradata/ORCLCDB' scope=both;
    ALTER SYSTEM SET log_archive_dest_1='LOCATION=/opt/oracle/oradata/ORCLCDB/ORCLPDB1/archive';
