apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: app
  name: localpvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi